name: winglink
services:
  postgres:
    image: 'postgres:alpine'
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}'
    volumes:
      - type: bind
        source: ./tmp-postgresql-data
        target: /var/lib/postgresql/data